{% set name = "pyCGNS" %}
{% set version = "6.3.4" %}

package:
  name: {{ name|lower }}-glob
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: a3aaf5a4116b38404bb3e1ab25d2e4afd7a73e6d633fa5dcc60bd5ff3fbaf583

build:
  number: 2
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython
    - meson-python
    - ninja
    - pkg-config
    - python-build
    - numpy
    - pip
    - hdf5
    - zlib
    - cmake

outputs:
  - name: {{ name|lower }}-core
    version: {{ version }}
    script: build_core.sh  # [not win]
    script: bld_core.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}

      host:
        - python
        - pip
        - python-build
        - meson-python
        - hdf5
        - zlib
        - numpy
        - cython
        - pkg-config
        - cmake

      run:
        - python
        - hdf5
        - numpy >=1.23.5

    test:
      imports:
        - CGNS.MAP
        - CGNS.PAT
        - CGNS.VAL

  - name: {{ name|lower }}
    version: {{ version }}
    script: build_all.sh  # [unix]
    script: bld_all.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}

      host:
        - python
        - pip
        - python-build
        - meson-python
        - hdf5
        - zlib
        - numpy
        - cython
        - pkg-config
        - qt6-main
        - qtpy
        - pyside6
        - vtk
        - cmake

      run:
        - python
        - hdf5
        - numpy >=1.23.5
        - qt6-main
        - qtpy
        - pyside6
        - vtk

    test:
      imports:
        - CGNS.MAP
        - CGNS.PAT
        - CGNS.VAL

about:
  home: https://github.com/pyCGNS/pyCGNS
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: pyCGNS provide a python interface to CGNS/SIDS datamodel for CGNS end-users and python application developpers
  doc_url: https://pycgns.github.io/
  dev_url: https://github.com/pyCGNS/pyCGNS

extra:
  recipe-maintainers:
    - MicK7
